# Copyright (C) 2008 Douglas Bagnall
#
# This file is part of Te Tuhi Video Game System, or Te Tuhi for short.
#
# Te Tuhi is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# Te Tuhi is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Te Tuhi.  If not, see <http://www.gnu.org/licenses/>.
- text:
    Press the button to try again
  delay: 1
  image: null

- text:
    "9"
  delay: 1
  image: null

- text:
    "8"
  delay: 1
  image: null

- text:
    "7"
  delay: 1
  image: null

- text:
    "6"
  delay: 1
  image: null

- text:
    "5"
  delay: 1
  image: null

- text:
    "4"
  delay: 1
  image: null

- text:
    "3"
  delay: 0.75
  image: null

- text:
    "hurry!"
  delay: 0.6
  image: null

- text:
    "2"
  delay: 0.65
  image: null

- text:
    "1"
  delay: 1
  image: null
